<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\BauaObservation;
use App\Models\ProtectedArea;

class BauaObservationSeeder extends Seeder
{
    /**
     * Run database seeds.
     */
    public function run(): void
    {
        $protectedArea = ProtectedArea::where('code', 'BWFR')->first();

        if (!$protectedArea) {
            $this->command->error('Protected area BWFR not found. Please run ProtectedAreaSeeder first.');
            return;
        }

        $observations = [
            // 2024 1st Semester
            ['transaction_code' => 'R2-BWFR-BMS', 'station_code' => 'R2-BWFR-BMS', 'patrol_year' => 2024, 'patrol_semester' => 1, 'bio_group' => 'flora', 'common_name' => 'White lauan', 'scientific_name' => 'Shorea contorta', 'recorded_count' => 4],
            ['transaction_code' => 'R2-BWFR-BMS', 'station_code' => 'R2-BWFR-BMS', 'patrol_year' => 2024, 'patrol_semester' => 1, 'bio_group' => 'flora', 'common_name' => 'Red lauan', 'scientific_name' => 'Shorea negrosensis', 'recorded_count' => 7],
            ['transaction_code' => 'R2-BWFR-BMS', 'station_code' => 'R2-BWFR-BMS', 'patrol_year' => 2024, 'patrol_semester' => 1, 'bio_group' => 'flora', 'common_name' => 'Mayapis', 'scientific_name' => 'Shorea palosapis', 'recorded_count' => 2],
            ['transaction_code' => 'R2-BWFR-BMS', 'station_code' => 'R2-BWFR-BMS', 'patrol_year' => 2024, 'patrol_semester' => 1, 'bio_group' => 'flora', 'common_name' => 'Tangile', 'scientific_name' => 'Shorea polysperma', 'recorded_count' => 5],
            ['transaction_code' => 'R2-BWFR-BMS', 'station_code' => 'R2-BWFR-BMS', 'patrol_year' => 2024, 'patrol_semester' => 1, 'bio_group' => 'flora', 'common_name' => 'Narra', 'scientific_name' => 'Pterocarpus indicus', 'recorded_count' => 18],
            ['transaction_code' => 'R2-BWFR-BMS', 'station_code' => 'R2-BWFR-BMS', 'patrol_year' => 2024, 'patrol_semester' => 1, 'bio_group' => 'flora', 'common_name' => 'Katmon', 'scientific_name' => 'Dillenia philippinensis', 'recorded_count' => 20],
            ['transaction_code' => 'R2-BWFR-BMS', 'station_code' => 'R2-BWFR-BMS', 'patrol_year' => 2024, 'patrol_semester' => 1, 'bio_group' => 'flora', 'common_name' => 'Tangisang-bayawak', 'scientific_name' => 'Ficus variegate', 'recorded_count' => 3],
            ['transaction_code' => 'R2-BWFR-BMS', 'station_code' => 'R2-BWFR-BMS', 'patrol_year' => 2024, 'patrol_semester' => 1, 'bio_group' => 'flora', 'common_name' => 'Nangka', 'scientific_name' => 'Arthocarpus heterophyllus', 'recorded_count' => 6],
            ['transaction_code' => 'R2-BWFR-BMS', 'station_code' => 'R2-BWFR-BMS', 'patrol_year' => 2024, 'patrol_semester' => 1, 'bio_group' => 'flora', 'common_name' => 'Binunga', 'scientific_name' => 'Macaranga tanarius', 'recorded_count' => 11],
            ['transaction_code' => 'R2-BWFR-BMS', 'station_code' => 'R2-BWFR-BMS', 'patrol_year' => 2024, 'patrol_semester' => 1, 'bio_group' => 'fauna', 'common_name' => 'Philippine coucal', 'scientific_name' => 'Centripus viridis', 'recorded_count' => 5],
            ['transaction_code' => 'R2-BWFR-BMS', 'station_code' => 'R2-BWFR-BMS', 'patrol_year' => 2024, 'patrol_semester' => 1, 'bio_group' => 'fauna', 'common_name' => 'Phil. Pygmy Swiflet', 'scientific_name' => 'Collocalia troglodytes', 'recorded_count' => 10],
            ['transaction_code' => 'R2-BWFR-BMS', 'station_code' => 'R2-BWFR-BMS', 'patrol_year' => 2024, 'patrol_semester' => 1, 'bio_group' => 'fauna', 'common_name' => 'Philippine bulbul', 'scientific_name' => 'Hypsipetes philippinus', 'recorded_count' => 30],
            ['transaction_code' => 'R2-BWFR-BMS', 'station_code' => 'R2-BWFR-BMS', 'patrol_year' => 2024, 'patrol_semester' => 1, 'bio_group' => 'fauna', 'common_name' => 'Crested Myna', 'scientific_name' => 'Acridotheres cristatellus', 'recorded_count' => 3],
            ['transaction_code' => 'R2-BWFR-BMS', 'station_code' => 'R2-BWFR-BMS', 'patrol_year' => 2024, 'patrol_semester' => 1, 'bio_group' => 'fauna', 'common_name' => 'Phil. Hawk Eagle', 'scientific_name' => 'Nisaetus philippensis', 'recorded_count' => 2],
            ['transaction_code' => 'R2-BWFR-BMS', 'station_code' => 'R2-BWFR-BMS', 'patrol_year' => 2024, 'patrol_semester' => 1, 'bio_group' => 'fauna', 'common_name' => 'White-Eared Brown Dove', 'scientific_name' => 'Paphitreron leucotis', 'recorded_count' => 2],
            ['transaction_code' => 'R2-BWFR-BMS', 'station_code' => 'R2-BWFR-BMS', 'patrol_year' => 2024, 'patrol_semester' => 1, 'bio_group' => 'fauna', 'common_name' => 'Dragonflies/ Dumsel fly', 'scientific_name' => '', 'recorded_count' => 8],
            ['transaction_code' => 'R2-BWFR-BMS', 'station_code' => 'R2-BWFR-BMS', 'patrol_year' => 2024, 'patrol_semester' => 1, 'bio_group' => 'fauna', 'common_name' => 'Grasshoppers', 'scientific_name' => '', 'recorded_count' => 2],
            ['transaction_code' => 'R2-BWFR-BMS', 'station_code' => 'R2-BWFR-BMS', 'patrol_year' => 2024, 'patrol_semester' => 1, 'bio_group' => 'fauna', 'common_name' => 'Butterflies', 'scientific_name' => '', 'recorded_count' => 15],
            ['transaction_code' => 'R2-BWFR-BMS', 'station_code' => 'R2-BWFR-BMS', 'patrol_year' => 2024, 'patrol_semester' => 1, 'bio_group' => 'fauna', 'common_name' => 'Coppersmith barbet', 'scientific_name' => 'Psilopogon haemacephalus', 'recorded_count' => 2],

            // 2024 2nd Semester
            ['transaction_code' => 'R2-BWFR-BMS', 'station_code' => 'R2-BWFR-BMS', 'patrol_year' => 2024, 'patrol_semester' => 2, 'bio_group' => 'flora', 'common_name' => 'Red lauan', 'scientific_name' => 'Shorea negrosensis', 'recorded_count' => 7],
            ['transaction_code' => 'R2-BWFR-BMS', 'station_code' => 'R2-BWFR-BMS', 'patrol_year' => 2024, 'patrol_semester' => 2, 'bio_group' => 'flora', 'common_name' => 'Mayapis', 'scientific_name' => 'Shorea palosapia', 'recorded_count' => 2],
            ['transaction_code' => 'R2-BWFR-BMS', 'station_code' => 'R2-BWFR-BMS', 'patrol_year' => 2024, 'patrol_semester' => 2, 'bio_group' => 'flora', 'common_name' => 'Narra', 'scientific_name' => 'Pterocarpus indicus', 'recorded_count' => 18],
            ['transaction_code' => 'R2-BWFR-BMS', 'station_code' => 'R2-BWFR-BMS', 'patrol_year' => 2024, 'patrol_semester' => 2, 'bio_group' => 'flora', 'common_name' => 'Tangile', 'scientific_name' => 'Shorea polysperma', 'recorded_count' => 5],
            ['transaction_code' => 'R2-BWFR-BMS', 'station_code' => 'R2-BWFR-BMS', 'patrol_year' => 2024, 'patrol_semester' => 2, 'bio_group' => 'flora', 'common_name' => 'Antipolo', 'scientific_name' => 'Artocarpus blancoi', 'recorded_count' => 6],
            ['transaction_code' => 'R2-BWFR-BMS', 'station_code' => 'R2-BWFR-BMS', 'patrol_year' => 2024, 'patrol_semester' => 2, 'bio_group' => 'fauna', 'common_name' => 'Dao (Dracontomelon dao)', 'scientific_name' => 'Bucerous hydrocorax', 'recorded_count' => 5],
            ['transaction_code' => 'R2-BWFR-BMS', 'station_code' => 'R2-BWFR-BMS', 'patrol_year' => 2024, 'patrol_semester' => 2, 'bio_group' => 'fauna', 'common_name' => 'Green Back/Trilling Tailorbird', 'scientific_name' => 'Orthotomus castaneiceps', 'recorded_count' => 9],
            ['transaction_code' => 'R2-BWFR-BMS', 'station_code' => 'R2-BWFR-BMS', 'patrol_year' => 2024, 'patrol_semester' => 2, 'bio_group' => 'fauna', 'common_name' => 'White-Eared Brown Dove (Alimukin', 'scientific_name' => 'Paphitreron leucotis', 'recorded_count' => 3],
            ['transaction_code' => 'R2-BWFR-BMS', 'station_code' => 'R2-BWFR-BMS', 'patrol_year' => 2024, 'patrol_semester' => 2, 'bio_group' => 'fauna', 'common_name' => 'Phil. Hawk Eagle', 'scientific_name' => 'Nisaetus philippinensis', 'recorded_count' => 1],
            ['transaction_code' => 'R2-BWFR-BMS', 'station_code' => 'R2-BWFR-BMS', 'patrol_year' => 2024, 'patrol_semester' => 2, 'bio_group' => 'fauna', 'common_name' => 'Phil. Hanging Parrot/Colasisi', 'scientific_name' => 'Loriculus philippensis', 'recorded_count' => 7],

            // 2025 1st Semester - Part 1
            ['transaction_code' => 'R2-BWFR-BMS', 'station_code' => 'R2-BWFR-BMS', 'patrol_year' => 2025, 'patrol_semester' => 1, 'bio_group' => 'flora', 'common_name' => 'White Lauan', 'scientific_name' => 'Shorea concorta', 'recorded_count' => 29],
            ['transaction_code' => 'R2-BWFR-BMS', 'station_code' => 'R2-BWFR-BMS', 'patrol_year' => 2025, 'patrol_semester' => 1, 'bio_group' => 'flora', 'common_name' => 'Red Lauan', 'scientific_name' => 'Shorea negrosensis', 'recorded_count' => 7],
            ['transaction_code' => 'R2-BWFR-BMS', 'station_code' => 'R2-BWFR-BMS', 'patrol_year' => 2025, 'patrol_semester' => 1, 'bio_group' => 'flora', 'common_name' => 'Mayapis', 'scientific_name' => 'Shorea palosapis', 'recorded_count' => 4],
            ['transaction_code' => 'R2-BWFR-BMS', 'station_code' => 'R2-BWFR-BMS', 'patrol_year' => 2025, 'patrol_semester' => 1, 'bio_group' => 'flora', 'common_name' => 'Narra', 'scientific_name' => 'Pterocarpus indicus', 'recorded_count' => 18],
            ['transaction_code' => 'R2-BWFR-BMS', 'station_code' => 'R2-BWFR-BMS', 'patrol_year' => 2025, 'patrol_semester' => 1, 'bio_group' => 'flora', 'common_name' => 'Tangile', 'scientific_name' => 'Shorea polysperma', 'recorded_count' => 5],
            ['transaction_code' => 'R2-BWFR-BMS', 'station_code' => 'R2-BWFR-BMS', 'patrol_year' => 2025, 'patrol_semester' => 1, 'bio_group' => 'flora', 'common_name' => 'Antiplolo', 'scientific_name' => 'Artocarpus blancoi', 'recorded_count' => 7],
            ['transaction_code' => 'R2-BWFR-BMS', 'station_code' => 'R2-BWFR-BMS', 'patrol_year' => 2025, 'patrol_semester' => 1, 'bio_group' => 'flora', 'common_name' => 'Dao', 'scientific_name' => 'Dracontomelon dao', 'recorded_count' => 15],
            ['transaction_code' => 'R2-BWFR-BMS', 'station_code' => 'R2-BWFR-BMS', 'patrol_year' => 2025, 'patrol_semester' => 1, 'bio_group' => 'flora', 'common_name' => 'White Lauan', 'scientific_name' => 'Shorea concorta', 'recorded_count' => 4],
            ['transaction_code' => 'R2-BWFR-BMS', 'station_code' => 'R2-BWFR-BMS', 'patrol_year' => 2025, 'patrol_semester' => 1, 'bio_group' => 'flora', 'common_name' => 'Red Lauan', 'scientific_name' => 'Shorea negrosensis', 'recorded_count' => 7],
            ['transaction_code' => 'R2-BWFR-BMS', 'station_code' => 'R2-BWFR-BMS', 'patrol_year' => 2025, 'patrol_semester' => 1, 'bio_group' => 'flora', 'common_name' => 'Mayapis', 'scientific_name' => 'Shorea palosapis', 'recorded_count' => 2],
            ['transaction_code' => 'R2-BWFR-BMS', 'station_code' => 'R2-BWFR-BMS', 'patrol_year' => 2025, 'patrol_semester' => 1, 'bio_group' => 'flora', 'common_name' => 'Narra', 'scientific_name' => 'Pterocarpus indicus', 'recorded_count' => 18],
            ['transaction_code' => 'R2-BWFR-BMS', 'station_code' => 'R2-BWFR-BMS', 'patrol_year' => 2025, 'patrol_semester' => 1, 'bio_group' => 'flora', 'common_name' => 'Tangile', 'scientific_name' => 'Shorea polysperma', 'recorded_count' => 5],
            ['transaction_code' => 'R2-BWFR-BMS', 'station_code' => 'R2-BWFR-BMS', 'patrol_year' => 2025, 'patrol_semester' => 1, 'bio_group' => 'flora', 'common_name' => 'Dao', 'scientific_name' => 'Dracontomelon dao', 'recorded_count' => 4],
            ['transaction_code' => 'R2-BWFR-BMS', 'station_code' => 'R2-BWFR-BMS', 'patrol_year' => 2025, 'patrol_semester' => 1, 'bio_group' => 'flora', 'common_name' => 'Antiplolo', 'scientific_name' => 'Artocarpus blancoi', 'recorded_count' => 6],
            ['transaction_code' => 'R2-BWFR-BMS', 'station_code' => 'R2-BWFR-BMS', 'patrol_year' => 2025, 'patrol_semester' => 1, 'bio_group' => 'flora', 'common_name' => 'Anabiong', 'scientific_name' => 'Trema orientalis', 'recorded_count' => 10],
            ['transaction_code' => 'R2-BWFR-BMS', 'station_code' => 'R2-BWFR-BMS', 'patrol_year' => 2025, 'patrol_semester' => 1, 'bio_group' => 'flora', 'common_name' => 'Binunga', 'scientific_name' => 'Macaranga tanarius', 'recorded_count' => 11],
            ['transaction_code' => 'R2-BWFR-BMS', 'station_code' => 'R2-BWFR-BMS', 'patrol_year' => 2025, 'patrol_semester' => 1, 'bio_group' => 'flora', 'common_name' => 'Hinlaumo', 'scientific_name' => 'Mallotus mollisimus', 'recorded_count' => 13],
            ['transaction_code' => 'R2-BWFR-BMS', 'station_code' => 'R2-BWFR-BMS', 'patrol_year' => 2025, 'patrol_semester' => 1, 'bio_group' => 'flora', 'common_name' => 'Alim', 'scientific_name' => 'Melanolepis multiglandulosa', 'recorded_count' => 6],
            ['transaction_code' => 'R2-BWFR-BMS', 'station_code' => 'R2-BWFR-BMS', 'patrol_year' => 2025, 'patrol_semester' => 1, 'bio_group' => 'flora', 'common_name' => 'Hauili', 'scientific_name' => 'Ficus septica', 'recorded_count' => 5],
            ['transaction_code' => 'R2-BWFR-BMS', 'station_code' => 'R2-BWFR-BMS', 'patrol_year' => 2025, 'patrol_semester' => 1, 'bio_group' => 'flora', 'common_name' => 'Tibig', 'scientific_name' => 'Ficus nota', 'recorded_count' => 20],
            ['transaction_code' => 'R2-BWFR-BMS', 'station_code' => 'R2-BWFR-BMS', 'patrol_year' => 2025, 'patrol_semester' => 1, 'bio_group' => 'flora', 'common_name' => 'Tangisang-bayawak', 'scientific_name' => 'Ficus variegata', 'recorded_count' => 3],
            ['transaction_code' => 'R2-BWFR-BMS', 'station_code' => 'R2-BWFR-BMS', 'patrol_year' => 2025, 'patrol_semester' => 1, 'bio_group' => 'flora', 'common_name' => 'Balite', 'scientific_name' => 'Ficus balete', 'recorded_count' => 2],
            ['transaction_code' => 'R2-BWFR-BMS', 'station_code' => 'R2-BWFR-BMS', 'patrol_year' => 2025, 'patrol_semester' => 1, 'bio_group' => 'flora', 'common_name' => 'Nangka', 'scientific_name' => 'Artocrpus heterophyllus', 'recorded_count' => 6],
            ['transaction_code' => 'R2-BWFR-BMS', 'station_code' => 'R2-BWFR-BMS', 'patrol_year' => 2025, 'patrol_semester' => 1, 'bio_group' => 'flora', 'common_name' => 'Kalumpit', 'scientific_name' => 'Terminalia microcarpa', 'recorded_count' => 1],
            ['transaction_code' => 'R2-BWFR-BMS', 'station_code' => 'R2-BWFR-BMS', 'patrol_year' => 2025, 'patrol_semester' => 1, 'bio_group' => 'flora', 'common_name' => 'Gmeina/Yemane', 'scientific_name' => 'Gmelina arborea', 'recorded_count' => 14],
            ['transaction_code' => 'R2-BWFR-BMS', 'station_code' => 'R2-BWFR-BMS', 'patrol_year' => 2025, 'patrol_semester' => 1, 'bio_group' => 'flora', 'common_name' => 'Lingu-lingo', 'scientific_name' => 'Vitex turczaninowii', 'recorded_count' => 1],
            ['transaction_code' => 'R2-BWFR-BMS', 'station_code' => 'R2-BWFR-BMS', 'patrol_year' => 2025, 'patrol_semester' => 1, 'bio_group' => 'flora', 'common_name' => 'Malaikmo', 'scientific_name' => 'Celtis philipensis', 'recorded_count' => 3],
            ['transaction_code' => 'R2-BWFR-BMS', 'station_code' => 'R2-BWFR-BMS', 'patrol_year' => 2025, 'patrol_semester' => 1, 'bio_group' => 'flora', 'common_name' => 'Katmon', 'scientific_name' => 'Dilenia philiphinensis', 'recorded_count' => 20],
            ['transaction_code' => 'R2-BWFR-BMS', 'station_code' => 'R2-BWFR-BMS', 'patrol_year' => 2025, 'patrol_semester' => 1, 'bio_group' => 'flora', 'common_name' => 'Falcata', 'scientific_name' => 'Falcataria falcata', 'recorded_count' => 1],
            ['transaction_code' => 'R2-BWFR-BMS', 'station_code' => 'R2-BWFR-BMS', 'patrol_year' => 2025, 'patrol_semester' => 1, 'bio_group' => 'flora', 'common_name' => 'Ipil-ipil', 'scientific_name' => 'Leucaena leucochephala', 'recorded_count' => 10],
            ['transaction_code' => 'R2-BWFR-BMS', 'station_code' => 'R2-BWFR-BMS', 'patrol_year' => 2025, 'patrol_semester' => 1, 'bio_group' => 'fauna', 'common_name' => 'Philippine bulbul', 'scientific_name' => 'Hypsipetes Philippinus', 'recorded_count' => 27],
            ['transaction_code' => 'R2-BWFR-BMS', 'station_code' => 'R2-BWFR-BMS', 'patrol_year' => 2025, 'patrol_semester' => 1, 'bio_group' => 'fauna', 'common_name' => 'Phil. Pygmy Swiflet', 'scientific_name' => 'Collocalia troglodytes', 'recorded_count' => 14],
            ['transaction_code' => 'R2-BWFR-BMS', 'station_code' => 'R2-BWFR-BMS', 'patrol_year' => 2025, 'patrol_semester' => 1, 'bio_group' => 'fauna', 'common_name' => 'Northern Rofous horn bill', 'scientific_name' => 'Bucerous hydrocorax', 'recorded_count' => 5],
            ['transaction_code' => 'R2-BWFR-BMS', 'station_code' => 'R2-BWFR-BMS', 'patrol_year' => 2025, 'patrol_semester' => 1, 'bio_group' => 'fauna', 'common_name' => 'Pygmy Flower pecker', 'scientific_name' => 'Dicaeum quadricolor', 'recorded_count' => 8],
            ['transaction_code' => 'R2-BWFR-BMS', 'station_code' => 'R2-BWFR-BMS', 'patrol_year' => 2025, 'patrol_semester' => 1, 'bio_group' => 'fauna', 'common_name' => 'Olived-backed sunbird', 'scientific_name' => 'Necratinia jugularis', 'recorded_count' => 17],
            ['transaction_code' => 'R2-BWFR-BMS', 'station_code' => 'R2-BWFR-BMS', 'patrol_year' => 2025, 'patrol_semester' => 1, 'bio_group' => 'fauna', 'common_name' => 'Green Back/Trilling Tailorbird (Phil. Tailor bird)', 'scientific_name' => 'Orthotomus castaneiceps', 'recorded_count' => 2],
            ['transaction_code' => 'R2-BWFR-BMS', 'station_code' => 'R2-BWFR-BMS', 'patrol_year' => 2025, 'patrol_semester' => 1, 'bio_group' => 'fauna', 'common_name' => 'Rufous-crowned Bee Eater (Blue Tailed Bee Eater)', 'scientific_name' => 'Merops philippinus', 'recorded_count' => 4],
            ['transaction_code' => 'R2-BWFR-BMS', 'station_code' => 'R2-BWFR-BMS', 'patrol_year' => 2025, 'patrol_semester' => 1, 'bio_group' => 'fauna', 'common_name' => 'Philippine hanging parrot', 'scientific_name' => 'Loriculus philippinensis', 'recorded_count' => 5],
            ['transaction_code' => 'R2-BWFR-BMS', 'station_code' => 'R2-BWFR-BMS', 'patrol_year' => 2025, 'patrol_semester' => 1, 'bio_group' => 'fauna', 'common_name' => 'Phil. Hawk Eagle', 'scientific_name' => 'Nisaetus philippinensis', 'recorded_count' => 2],
            ['transaction_code' => 'R2-BWFR-BMS', 'station_code' => 'R2-BWFR-BMS', 'patrol_year' => 2025, 'patrol_semester' => 1, 'bio_group' => 'fauna', 'common_name' => 'White -Eard Brown Dove (Alimukin)', 'scientific_name' => 'Paphitreron leucotis', 'recorded_count' => 2],
            ['transaction_code' => 'R2-BWFR-BMS', 'station_code' => 'R2-BWFR-BMS', 'patrol_year' => 2025, 'patrol_semester' => 1, 'bio_group' => 'fauna', 'common_name' => 'Cicada', 'scientific_name' => '', 'recorded_count' => 7],
            ['transaction_code' => 'R2-BWFR-BMS', 'station_code' => 'R2-BWFR-BMS', 'patrol_year' => 2025, 'patrol_semester' => 1, 'bio_group' => 'fauna', 'common_name' => 'Butterflies', 'scientific_name' => '', 'recorded_count' => 12],
            ['transaction_code' => 'R2-BWFR-BMS', 'station_code' => 'R2-BWFR-BMS', 'patrol_year' => 2025, 'patrol_semester' => 1, 'bio_group' => 'fauna', 'common_name' => 'Dragonflies/Dumsel fly', 'scientific_name' => '', 'recorded_count' => 5],
            ['transaction_code' => 'R2-BWFR-BMS', 'station_code' => 'R2-BWFR-BMS', 'patrol_year' => 2025, 'patrol_semester' => 1, 'bio_group' => 'fauna', 'common_name' => 'Grasshoppers', 'scientific_name' => '', 'recorded_count' => 2],

            // 2025 1st Semester - Part 2 (duplicate entries from data)
            ['transaction_code' => 'R2-BWFR-BMS', 'station_code' => 'R2-BWFR-BMS', 'patrol_year' => 2025, 'patrol_semester' => 1, 'bio_group' => 'fauna', 'common_name' => 'Northern Rofous horn bill', 'scientific_name' => 'Bucerous hydrocorax', 'recorded_count' => 5],
            ['transaction_code' => 'R2-BWFR-BMS', 'station_code' => 'R2-BWFR-BMS', 'patrol_year' => 2025, 'patrol_semester' => 1, 'bio_group' => 'fauna', 'common_name' => 'Philippine bulbul', 'scientific_name' => 'Hypsipetes Philippinus', 'recorded_count' => 30],
            ['transaction_code' => 'R2-BWFR-BMS', 'station_code' => 'R2-BWFR-BMS', 'patrol_year' => 2025, 'patrol_semester' => 1, 'bio_group' => 'fauna', 'common_name' => 'Phil. Pygmy Swiflet', 'scientific_name' => 'Collocalia troglodytes', 'recorded_count' => 10],
            ['transaction_code' => 'R2-BWFR-BMS', 'station_code' => 'R2-BWFR-BMS', 'patrol_year' => 2025, 'patrol_semester' => 1, 'bio_group' => 'fauna', 'common_name' => 'Philippine coucal', 'scientific_name' => 'Centripus viridis', 'recorded_count' => 7],
            ['transaction_code' => 'R2-BWFR-BMS', 'station_code' => 'R2-BWFR-BMS', 'patrol_year' => 2025, 'patrol_semester' => 1, 'bio_group' => 'fauna', 'common_name' => 'Olived-backed sunbird', 'scientific_name' => 'Necratinia jugularis', 'recorded_count' => 13],
            ['transaction_code' => 'R2-BWFR-BMS', 'station_code' => 'R2-BWFR-BMS', 'patrol_year' => 2025, 'patrol_semester' => 1, 'bio_group' => 'fauna', 'common_name' => 'Crested Myna', 'scientific_name' => 'Acridotheres cristatellus', 'recorded_count' => 3],
            ['transaction_code' => 'R2-BWFR-BMS', 'station_code' => 'R2-BWFR-BMS', 'patrol_year' => 2025, 'patrol_semester' => 1, 'bio_group' => 'fauna', 'common_name' => 'Green Back/Trilling Tailorbird (Phil. Tailor bird)', 'scientific_name' => 'Orthotomus castaneiceps', 'recorded_count' => 3],
            ['transaction_code' => 'R2-BWFR-BMS', 'station_code' => 'R2-BWFR-BMS', 'patrol_year' => 2025, 'patrol_semester' => 1, 'bio_group' => 'fauna', 'common_name' => 'Rufous-crowned Bee Eater (Blue Tailed Bee Eater)', 'scientific_name' => 'Merops philippinus', 'recorded_count' => 1],
            ['transaction_code' => 'R2-BWFR-BMS', 'station_code' => 'R2-BWFR-BMS', 'patrol_year' => 2025, 'patrol_semester' => 1, 'bio_group' => 'fauna', 'common_name' => 'Phil. Hawk Eagle', 'scientific_name' => 'Nisaetus philippinensis', 'recorded_count' => 2],
            ['transaction_code' => 'R2-BWFR-BMS', 'station_code' => 'R2-BWFR-BMS', 'patrol_year' => 2025, 'patrol_semester' => 1, 'bio_group' => 'fauna', 'common_name' => 'Pygmy Flower pecker', 'scientific_name' => 'Dicaeum quadricolor', 'recorded_count' => 7],
            ['transaction_code' => 'R2-BWFR-BMS', 'station_code' => 'R2-BWFR-BMS', 'patrol_year' => 2025, 'patrol_semester' => 1, 'bio_group' => 'fauna', 'common_name' => 'Philippine hanging parrot', 'scientific_name' => 'Loriculus philippinensis', 'recorded_count' => 8],
            ['transaction_code' => 'R2-BWFR-BMS', 'station_code' => 'R2-BWFR-BMS', 'patrol_year' => 2025, 'patrol_semester' => 1, 'bio_group' => 'fauna', 'common_name' => 'Coppersmith barbet', 'scientific_name' => 'Psilopogon hemacephalus', 'recorded_count' => 2],
            ['transaction_code' => 'R2-BWFR-BMS', 'station_code' => 'R2-BWFR-BMS', 'patrol_year' => 2025, 'patrol_semester' => 1, 'bio_group' => 'fauna', 'common_name' => 'White -Eard Brown Dove (Alimukin)', 'scientific_name' => 'Paphitreron leucotis', 'recorded_count' => 2],
            ['transaction_code' => 'R2-BWFR-BMS', 'station_code' => 'R2-BWFR-BMS', 'patrol_year' => 2025, 'patrol_semester' => 1, 'bio_group' => 'fauna', 'common_name' => 'Cicada', 'scientific_name' => '', 'recorded_count' => 10],
            ['transaction_code' => 'R2-BWFR-BMS', 'station_code' => 'R2-BWFR-BMS', 'patrol_year' => 2025, 'patrol_semester' => 1, 'bio_group' => 'fauna', 'common_name' => 'Butterflies', 'scientific_name' => '', 'recorded_count' => 15],
            ['transaction_code' => 'R2-BWFR-BMS', 'station_code' => 'R2-BWFR-BMS', 'patrol_year' => 2025, 'patrol_semester' => 1, 'bio_group' => 'fauna', 'common_name' => 'Dragonflies/Dumsel fly', 'scientific_name' => '', 'recorded_count' => 8],
            ['transaction_code' => 'R2-BWFR-BMS', 'station_code' => 'R2-BWFR-BMS', 'patrol_year' => 2025, 'patrol_semester' => 1, 'bio_group' => 'fauna', 'common_name' => 'Grasshoppers', 'scientific_name' => '', 'recorded_count' => 2],
            ['transaction_code' => 'R2-BWFR-BMS', 'station_code' => 'R2-BWFR-BMS', 'patrol_year' => 2025, 'patrol_semester' => 1, 'bio_group' => 'fauna', 'common_name' => 'Pygmy Flower pecker', 'scientific_name' => 'Dicaeum quadricolor', 'recorded_count' => 11],
            ['transaction_code' => 'R2-BWFR-BMS', 'station_code' => 'R2-BWFR-BMS', 'patrol_year' => 2025, 'patrol_semester' => 1, 'bio_group' => 'fauna', 'common_name' => 'Philippine bulbul', 'scientific_name' => 'Hypsipetes Philippinus', 'recorded_count' => 20],
            ['transaction_code' => 'R2-BWFR-BMS', 'station_code' => 'R2-BWFR-BMS', 'patrol_year' => 2025, 'patrol_semester' => 1, 'bio_group' => 'fauna', 'common_name' => 'Olived-backed sunbird', 'scientific_name' => 'Necratinia jugularis', 'recorded_count' => 11],
            ['transaction_code' => 'R2-BWFR-BMS', 'station_code' => 'R2-BWFR-BMS', 'patrol_year' => 2025, 'patrol_semester' => 1, 'bio_group' => 'fauna', 'common_name' => 'Rufous-crowned Bee Eater (Blue Tailed Bee Eater)', 'scientific_name' => 'Merops philippinus', 'recorded_count' => 1],
            ['transaction_code' => 'R2-BWFR-BMS', 'station_code' => 'R2-BWFR-BMS', 'patrol_year' => 2025, 'patrol_semester' => 1, 'bio_group' => 'fauna', 'common_name' => 'Philippine hanging parrot', 'scientific_name' => 'Loriculus philippinensis', 'recorded_count' => 2],
            ['transaction_code' => 'R2-BWFR-BMS', 'station_code' => 'R2-BWFR-BMS', 'patrol_year' => 2025, 'patrol_semester' => 1, 'bio_group' => 'fauna', 'common_name' => 'Phil. Hawk Eagle', 'scientific_name' => 'Nisaetus philippinensis', 'recorded_count' => 2],
            ['transaction_code' => 'R2-BWFR-BMS', 'station_code' => 'R2-BWFR-BMS', 'patrol_year' => 2025, 'patrol_semester' => 1, 'bio_group' => 'fauna', 'common_name' => 'White -Eard Brown Dove (Alimukin)', 'scientific_name' => 'Paphitreron leucotis', 'recorded_count' => 1],
            ['transaction_code' => 'R2-BWFR-BMS', 'station_code' => 'R2-BWFR-BMS', 'patrol_year' => 2025, 'patrol_semester' => 1, 'bio_group' => 'fauna', 'common_name' => 'Cicada', 'scientific_name' => '', 'recorded_count' => 3],
            ['transaction_code' => 'R2-BWFR-BMS', 'station_code' => 'R2-BWFR-BMS', 'patrol_year' => 2025, 'patrol_semester' => 1, 'bio_group' => 'fauna', 'common_name' => 'Butterflies', 'scientific_name' => '', 'recorded_count' => 13],

            // 2025 2nd Semester - Flora
            ['transaction_code' => 'R2-BWFR-BMS', 'station_code' => 'R2-BWFR-BMS', 'patrol_year' => 2025, 'patrol_semester' => 2, 'bio_group' => 'flora', 'common_name' => 'Amugis', 'scientific_name' => 'Koordersiodendron pinnatum', 'recorded_count' => 2],
            ['transaction_code' => 'R2-BWFR-BMS', 'station_code' => 'R2-BWFR-BMS', 'patrol_year' => 2025, 'patrol_semester' => 2, 'bio_group' => 'flora', 'common_name' => 'Apitong', 'scientific_name' => 'Dipterocarpus grandiflorus', 'recorded_count' => 19],
            ['transaction_code' => 'R2-BWFR-BMS', 'station_code' => 'R2-BWFR-BMS', 'patrol_year' => 2025, 'patrol_semester' => 2, 'bio_group' => 'flora', 'common_name' => 'Bolong-eta', 'scientific_name' => 'Diospyros pilosanthera', 'recorded_count' => 1],
            ['transaction_code' => 'R2-BWFR-BMS', 'station_code' => 'R2-BWFR-BMS', 'patrol_year' => 2025, 'patrol_semester' => 2, 'bio_group' => 'flora', 'common_name' => 'Dao', 'scientific_name' => 'Dracontomelon dao', 'recorded_count' => 4],
            ['transaction_code' => 'R2-BWFR-BMS', 'station_code' => 'R2-BWFR-BMS', 'patrol_year' => 2025, 'patrol_semester' => 2, 'bio_group' => 'flora', 'common_name' => 'Guijo', 'scientific_name' => 'Shorea guiso', 'recorded_count' => 1],
            ['transaction_code' => 'R2-BWFR-BMS', 'station_code' => 'R2-BWFR-BMS', 'patrol_year' => 2025, 'patrol_semester' => 2, 'bio_group' => 'flora', 'common_name' => 'Kalantas', 'scientific_name' => 'Toona kalantas', 'recorded_count' => 1],
            ['transaction_code' => 'R2-BWFR-BMS', 'station_code' => 'R2-BWFR-BMS', 'patrol_year' => 2025, 'patrol_semester' => 2, 'bio_group' => 'flora', 'common_name' => 'Laneteng Gubat', 'scientific_name' => 'Kibatalia gitingensis', 'recorded_count' => 5],
            ['transaction_code' => 'R2-BWFR-BMS', 'station_code' => 'R2-BWFR-BMS', 'patrol_year' => 2025, 'patrol_semester' => 2, 'bio_group' => 'flora', 'common_name' => 'Makaasim', 'scientific_name' => 'Syzygium nitidum', 'recorded_count' => 30],
            ['transaction_code' => 'R2-BWFR-BMS', 'station_code' => 'R2-BWFR-BMS', 'patrol_year' => 2025, 'patrol_semester' => 2, 'bio_group' => 'flora', 'common_name' => 'Malabayyabas', 'scientific_name' => 'Tristaniopsis decorticata', 'recorded_count' => 87],
            ['transaction_code' => 'R2-BWFR-BMS', 'station_code' => 'R2-BWFR-BMS', 'patrol_year' => 2025, 'patrol_semester' => 2, 'bio_group' => 'flora', 'common_name' => 'Malaruhat', 'scientific_name' => 'Syzygium nervosum', 'recorded_count' => 36],
            ['transaction_code' => 'R2-BWFR-BMS', 'station_code' => 'R2-BWFR-BMS', 'patrol_year' => 2025, 'patrol_semester' => 2, 'bio_group' => 'flora', 'common_name' => 'Mayapis', 'scientific_name' => 'Shorea palosapis', 'recorded_count' => 2],
            ['transaction_code' => 'R2-BWFR-BMS', 'station_code' => 'R2-BWFR-BMS', 'patrol_year' => 2025, 'patrol_semester' => 2, 'bio_group' => 'flora', 'common_name' => 'Molave', 'scientific_name' => 'Vitex parviflora', 'recorded_count' => 1],
            ['transaction_code' => 'R2-BWFR-BMS', 'station_code' => 'R2-BWFR-BMS', 'patrol_year' => 2025, 'patrol_semester' => 2, 'bio_group' => 'flora', 'common_name' => 'Pangomboien', 'scientific_name' => 'Syzygium simile', 'recorded_count' => 34],
            ['transaction_code' => 'R2-BWFR-BMS', 'station_code' => 'R2-BWFR-BMS', 'patrol_year' => 2025, 'patrol_semester' => 2, 'bio_group' => 'flora', 'common_name' => 'Red Lauan', 'scientific_name' => 'Shorea negrosensis', 'recorded_count' => 32],
            ['transaction_code' => 'R2-BWFR-BMS', 'station_code' => 'R2-BWFR-BMS', 'patrol_year' => 2025, 'patrol_semester' => 2, 'bio_group' => 'flora', 'common_name' => 'Tanguile', 'scientific_name' => 'Shorea polysperma', 'recorded_count' => 20],
            ['transaction_code' => 'R2-BWFR-BMS', 'station_code' => 'R2-BWFR-BMS', 'patrol_year' => 2025, 'patrol_semester' => 2, 'bio_group' => 'flora', 'common_name' => 'Tuai', 'scientific_name' => 'Bischofia javanica', 'recorded_count' => 6],
            ['transaction_code' => 'R2-BWFR-BMS', 'station_code' => 'R2-BWFR-BMS', 'patrol_year' => 2025, 'patrol_semester' => 2, 'bio_group' => 'flora', 'common_name' => 'White lauan', 'scientific_name' => 'Shorea contorta', 'recorded_count' => 51],
            ['transaction_code' => 'R2-BWFR-BMS', 'station_code' => 'R2-BWFR-BMS', 'patrol_year' => 2025, 'patrol_semester' => 2, 'bio_group' => 'flora', 'common_name' => 'Alahan', 'scientific_name' => 'Guioa koelreuteria', 'recorded_count' => 1],
            ['transaction_code' => 'R2-BWFR-BMS', 'station_code' => 'R2-BWFR-BMS', 'patrol_year' => 2025, 'patrol_semester' => 2, 'bio_group' => 'flora', 'common_name' => 'Balete', 'scientific_name' => 'Ficus balete', 'recorded_count' => 4],
            ['transaction_code' => 'R2-BWFR-BMS', 'station_code' => 'R2-BWFR-BMS', 'patrol_year' => 2025, 'patrol_semester' => 2, 'bio_group' => 'flora', 'common_name' => 'Balinghasai', 'scientific_name' => 'Buchania arborescens', 'recorded_count' => 11],
            ['transaction_code' => 'R2-BWFR-BMS', 'station_code' => 'R2-BWFR-BMS', 'patrol_year' => 2025, 'patrol_semester' => 2, 'bio_group' => 'flora', 'common_name' => 'Lagapak', 'scientific_name' => 'Macaranga hispida', 'recorded_count' => 12],
            ['transaction_code' => 'R2-BWFR-BMS', 'station_code' => 'R2-BWFR-BMS', 'patrol_year' => 2025, 'patrol_semester' => 2, 'bio_group' => 'flora', 'common_name' => 'Kalumpit', 'scientific_name' => 'Terminalia macrocarpa', 'recorded_count' => 1],
            ['transaction_code' => 'R2-BWFR-BMS', 'station_code' => 'R2-BWFR-BMS', 'patrol_year' => 2025, 'patrol_semester' => 2, 'bio_group' => 'flora', 'common_name' => 'Katmon', 'scientific_name' => 'Dillenia philippinensis', 'recorded_count' => 27],
            ['transaction_code' => 'R2-BWFR-BMS', 'station_code' => 'R2-BWFR-BMS', 'patrol_year' => 2025, 'patrol_semester' => 2, 'bio_group' => 'flora', 'common_name' => 'Lingu-lingo', 'scientific_name' => 'Vitex turczaninowii', 'recorded_count' => 8],
            ['transaction_code' => 'R2-BWFR-BMS', 'station_code' => 'R2-BWFR-BMS', 'patrol_year' => 2025, 'patrol_semester' => 2, 'bio_group' => 'flora', 'common_name' => 'Malatungaw', 'scientific_name' => 'Melastoma caveleriei', 'recorded_count' => 11],
            ['transaction_code' => 'R2-BWFR-BMS', 'station_code' => 'R2-BWFR-BMS', 'patrol_year' => 2025, 'patrol_semester' => 2, 'bio_group' => 'flora', 'common_name' => 'Piling liitan', 'scientific_name' => 'Canarium luzonicum', 'recorded_count' => 3],
            ['transaction_code' => 'R2-BWFR-BMS', 'station_code' => 'R2-BWFR-BMS', 'patrol_year' => 2025, 'patrol_semester' => 2, 'bio_group' => 'flora', 'common_name' => 'Sablot', 'scientific_name' => 'Litsea glutinosa', 'recorded_count' => 1],
            ['transaction_code' => 'R2-BWFR-BMS', 'station_code' => 'R2-BWFR-BMS', 'patrol_year' => 2025, 'patrol_semester' => 2, 'bio_group' => 'flora', 'common_name' => 'Tagpong gubat', 'scientific_name' => 'Psychotria luzoniensis', 'recorded_count' => 7],
            ['transaction_code' => 'R2-BWFR-BMS', 'station_code' => 'R2-BWFR-BMS', 'patrol_year' => 2025, 'patrol_semester' => 2, 'bio_group' => 'flora', 'common_name' => 'Takip-asin', 'scientific_name' => 'Macaranga grandifolia', 'recorded_count' => 5],

            // 2025 2nd Semester - Fauna
            ['transaction_code' => 'R2-BWFR-BMS', 'station_code' => 'R2-BWFR-BMS', 'patrol_year' => 2025, 'patrol_semester' => 2, 'bio_group' => 'fauna', 'common_name' => 'Indigo-Banded King Fisher', 'scientific_name' => 'Ceyx cyanopectus', 'recorded_count' => 1],
            ['transaction_code' => 'R2-BWFR-BMS', 'station_code' => 'R2-BWFR-BMS', 'patrol_year' => 2025, 'patrol_semester' => 2, 'bio_group' => 'fauna', 'common_name' => 'White-eared Brown dove', 'scientific_name' => 'Phapitreron leucotis', 'recorded_count' => 5],
            ['transaction_code' => 'R2-BWFR-BMS', 'station_code' => 'R2-BWFR-BMS', 'patrol_year' => 2025, 'patrol_semester' => 2, 'bio_group' => 'fauna', 'common_name' => 'Amethyst Brown Dove', 'scientific_name' => 'Phapitreron amethystinus', 'recorded_count' => 3],
            ['transaction_code' => 'R2-BWFR-BMS', 'station_code' => 'R2-BWFR-BMS', 'patrol_year' => 2025, 'patrol_semester' => 2, 'bio_group' => 'fauna', 'common_name' => 'Balicassiao', 'scientific_name' => 'Nisaetus philippinensis', 'recorded_count' => 1],
            ['transaction_code' => 'R2-BWFR-BMS', 'station_code' => 'R2-BWFR-BMS', 'patrol_year' => 2025, 'patrol_semester' => 2, 'bio_group' => 'fauna', 'common_name' => 'Pygmy Flower Pecker', 'scientific_name' => 'Dicaeum pygmaeum', 'recorded_count' => 3],
            ['transaction_code' => 'R2-BWFR-BMS', 'station_code' => 'R2-BWFR-BMS', 'patrol_year' => 2025, 'patrol_semester' => 2, 'bio_group' => 'fauna', 'common_name' => 'Northern Rufous Hornbill', 'scientific_name' => 'Buceros hydrocorax', 'recorded_count' => 8],
            ['transaction_code' => 'R2-BWFR-BMS', 'station_code' => 'R2-BWFR-BMS', 'patrol_year' => 2025, 'patrol_semester' => 2, 'bio_group' => 'fauna', 'common_name' => 'Philippine Bulbul', 'scientific_name' => 'Hypsipetes philippinus', 'recorded_count' => 12],
            ['transaction_code' => 'R2-BWFR-BMS', 'station_code' => 'R2-BWFR-BMS', 'patrol_year' => 2025, 'patrol_semester' => 2, 'bio_group' => 'fauna', 'common_name' => 'Philippine Fairy-bluebird', 'scientific_name' => 'Irena cyanogastra', 'recorded_count' => 2],
            ['transaction_code' => 'R2-BWFR-BMS', 'station_code' => 'R2-BWFR-BMS', 'patrol_year' => 2025, 'patrol_semester' => 2, 'bio_group' => 'fauna', 'common_name' => 'Olive-backed Sunbird', 'scientific_name' => 'Necratinia jugularis', 'recorded_count' => 10],
            ['transaction_code' => 'R2-BWFR-BMS', 'station_code' => 'R2-BWFR-BMS', 'patrol_year' => 2025, 'patrol_semester' => 2, 'bio_group' => 'fauna', 'common_name' => 'Green-backed Tailorbird', 'scientific_name' => 'Orthotomus castaneiceps', 'recorded_count' => 8],
            ['transaction_code' => 'R2-BWFR-BMS', 'station_code' => 'R2-BWFR-BMS', 'patrol_year' => 2025, 'patrol_semester' => 2, 'bio_group' => 'fauna', 'common_name' => 'Rufous-crowned Bee Eater', 'scientific_name' => 'Merups americanus', 'recorded_count' => 9],
            ['transaction_code' => 'R2-BWFR-BMS', 'station_code' => 'R2-BWFR-BMS', 'patrol_year' => 2025, 'patrol_semester' => 2, 'bio_group' => 'fauna', 'common_name' => 'Philippine Hawk Eagle', 'scientific_name' => 'Nisaetus philippinensis', 'recorded_count' => 1],
            ['transaction_code' => 'R2-BWFR-BMS', 'station_code' => 'R2-BWFR-BMS', 'patrol_year' => 2025, 'patrol_semester' => 2, 'bio_group' => 'fauna', 'common_name' => 'Juvenile Snake (Color Black & Brown)', 'scientific_name' => '', 'recorded_count' => 1],
            ['transaction_code' => 'R2-BWFR-BMS', 'station_code' => 'R2-BWFR-BMS', 'patrol_year' => 2025, 'patrol_semester' => 2, 'bio_group' => 'fauna', 'common_name' => 'Common Sun Skink (Bubuli)', 'scientific_name' => '', 'recorded_count' => 2],
            ['transaction_code' => 'R2-BWFR-BMS', 'station_code' => 'R2-BWFR-BMS', 'patrol_year' => 2025, 'patrol_semester' => 1, 'bio_group' => 'fauna', 'common_name' => 'Dragonflies/Dumsel fly', 'scientific_name' => '', 'recorded_count' => 5],
            ['transaction_code' => 'R2-BWFR-BMS', 'station_code' => 'R2-BWFR-BMS', 'patrol_year' => 2025, 'patrol_semester' => 1, 'bio_group' => 'fauna', 'common_name' => 'Grasshoppers', 'scientific_name' => '', 'recorded_count' => 2],
        ];

        foreach ($observations as $observation) {
            $observation['protected_area_id'] = $protectedArea->id;
            BauaObservation::create($observation);
        }

        $this->command->info('Baua observations seeded successfully!');
    }
}
